### ISSUE TITLE
object.class was renamed to object.type in 1.9

### ISSUE THREAD

**Issue by TatriX** [Zer0-One/libtmj#2]
Hi!
Based on [the docs](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#object) `Class` property of the object is stored as `type` since 1.9

I renamed the field in my local build, but probably it should be read based on the map's version.

**Comment by Zer0-One** [comment]
I haven't had much time to work on this lib, so I think I might just track whatever the latest stable version of Tiled does, to keep things simple.

**Comment by Zer0-One** [comment]
Should be fixed by 9699ee0 .

If you have a 1.10 sample map/tileset you can add to the examples and tests, that would be much appreciated.
